/**
 * Scale positions generated by one rule, no shape tables: take consecutive scale notes upward
 * from a starting degree on string 6 and give each string exactly N of them, low to high.
 * N = 2 on a pentatonic gives the five boxes (K3.4); N = 3 on a 7-note scale gives the seven
 * three-notes-per-string positions (K2.9). The B-string kink falls out of the pitch math.
 */
import {
  degreeOf,
  interval,
  mod,
  pc,
  scaleNotes,
  scaleSemitones,
  transpose,
  SCALES,
  type DegreeLabel,
  type NoteName,
  type Pitch,
  type ScaleId,
} from '../music';
import { homeFret, openMidi, pitchAtPos, STRINGS, type FretPos, type StringNumber } from './neck';

export interface PositionNote extends FretPos {
  readonly pitch: Pitch;
  /** Degree label over the scale's tonic: '1', 'b3', 'b5'… */
  readonly degree: DegreeLabel;
  readonly isTonic: boolean;
  /** Added tone of a decorated scale, e.g. the blues ♭5 (K6.1). */
  readonly isDecoration: boolean;
}

export interface Position {
  /** 1-based. Box 1 has the anchor note on string 6 under the first finger. */
  readonly index: number;
  readonly notes: readonly PositionNote[];
  readonly minFret: number;
  readonly maxFret: number;
}

export interface PositionOptions {
  readonly tonic: NoteName;
  readonly scale: ScaleId;
  /** 2 for pentatonic boxes, 3 for three-notes-per-string. */
  readonly notesPerString: 2 | 3;
  /**
   * Note that starts position 1 on string 6. Defaults to the tonic, except for major pentatonic
   * and major blues, which use their relative minor so box numbers match the minor boxes —
   * the same shapes, as in the book (K3.4).
   */
  readonly anchor?: NoteName;
}

/** Positions sitting entirely above this fret are moved down an octave. */
const WRAP_ABOVE = 12;

export function defaultAnchor(tonic: NoteName, scale: ScaleId): NoteName {
  const base = SCALES[scale].base ?? scale;
  return base === 'majorPentatonic' ? transpose(tonic, interval('6')) : tonic;
}

export function positions(opts: PositionOptions): Position[] {
  const { tonic, scale, notesPerString } = opts;
  const base = SCALES[scale].base ?? scale;
  const anchor = opts.anchor ?? defaultAnchor(tonic, scale);
  const context = scaleNotes(tonic, scale);
  const basePcs = new Set(scaleSemitones(base).map((s) => mod(pc(tonic) + s, 12)));
  const decoPcs = new Set(
    scaleSemitones(scale)
      .map((s) => mod(pc(tonic) + s, 12))
      .filter((p) => !basePcs.has(p)),
  );

  const low = openMidi(6);
  const ladder: number[] = [];
  for (let m = low; m <= low + 60; m++) if (basePcs.has(mod(m, 12))) ladder.push(m);
  const start = ladder.indexOf(low + homeFret(anchor, 6));
  const perPosition = notesPerString * STRINGS.length;

  const note = (pos: FretPos, isDecoration: boolean): PositionNote => {
    const pitch = pitchAtPos(pos, context);
    return { ...pos, pitch, degree: degreeOf(tonic, pitch), isTonic: pc(pitch) === pc(tonic), isDecoration };
  };

  return Array.from({ length: basePcs.size }, (_, k) => {
    const run = ladder.slice(start + k, start + k + perPosition);
    let cells: FretPos[] = run.map((m, i) => {
      const string = STRINGS[Math.floor(i / notesPerString)]!;
      return { string, fret: m - openMidi(string) };
    });
    const lowest = Math.min(...cells.map((c) => c.fret));
    if (lowest > WRAP_ABOVE) cells = cells.map((c) => ({ ...c, fret: c.fret - 12 }));

    const minFret = Math.min(...cells.map((c) => c.fret));
    const maxFret = Math.max(...cells.map((c) => c.fret));
    const notes = cells.map((c) => note(c, false));

    // Blue notes go inside the box, never widening it.
    for (const s of STRINGS) {
      for (let f = minFret; f <= maxFret; f++) {
        if (decoPcs.has(mod(openMidi(s) + f, 12))) notes.push(note({ string: s, fret: f }, true));
      }
    }
    notes.sort((a, b) => openMidi(a.string) + a.fret - (openMidi(b.string) + b.fret));
    return { index: k + 1, notes, minFret, maxFret };
  });
}

/**
 * Frets to slide every shape when changing key, the shortest way (−6…+5). K3.5.
 * Compares home frets on string 6 of the two tonics.
 */
export function keyShift(from: NoteName, to: NoteName): number {
  const d = mod(homeFret(to, 6) - homeFret(from, 6), 12);
  return d > 5 ? d - 12 : d;
}

export type { StringNumber };
