/**
 * A name for every concept ID in docs/theory-knowledge, shown next to a step's number so a
 * learner can look the idea up. Names use the standard terms a search finds; Vietnamese follows
 * the glossary in docs/theory-knowledge/README.md (English terms where players use them).
 */
import type { Lang } from '../i18n';
import type { ConceptId } from './types';

const en = {
  'K0.1': 'Guitar string names and numbers',
  'K0.2': 'Frets and semitones',
  'K0.3': 'Reading tab and chord diagrams',
  'K0.4': 'The fifth-fret rule and the G–B shift',
  'K0.5': 'Note names, sharps, flats and enharmonics',
  'K0.6': 'Octave shapes',
  'K0.7': 'Notes on the 6th and 5th strings',
  'K0.8': 'Fretting-hand position and finger exercises',
  'K1.1': 'Beat, tempo and bars',
  'K1.2': 'Note values and rests',
  'K1.3': 'Counting rhythms',
  'K1.4': 'Strumming patterns and alternate picking',
  'K1.5': 'Triplets, swing and shuffle',
  'K2.1': 'The major scale',
  'K2.2': 'Spelling scales and key signatures',
  'K2.3': 'Intervals: names and semitones',
  'K2.4': 'Interval shapes on the fretboard',
  'K2.5': 'Double sharps, double flats and note spelling',
  'K2.6': 'Compound intervals: 9ths, 11ths, 13ths',
  'K2.7': 'The natural minor scale',
  'K2.8': 'Relative major and minor keys',
  'K2.9': 'Three-notes-per-string scales',
  'K3.1': 'Major pentatonic scale',
  'K3.2': 'Minor pentatonic scale',
  'K3.3': 'Relative major and minor pentatonic',
  'K3.4': 'The five pentatonic boxes',
  'K3.5': 'Connecting pentatonic boxes and changing key',
  'K3.6': 'Pentatonic sequences',
  'K3.7': 'Choosing major or minor pentatonic',
  'K4.1': 'Triads',
  'K4.2': 'Power chords',
  'K4.3': 'Seventh chords',
  'K4.4': 'Extended and add chords',
  'K4.5': 'Open chords',
  'K4.6': 'Movable barre chords',
  'K4.7': 'Inversions and slash chords',
  'K4.8': 'Chord substitution and simplifying chords',
  'K4.9': 'Chord extensions and altered notes',
  'K5.1': 'Keys and the tonic',
  'K5.2': 'Diatonic chords in a major key',
  'K5.3': 'Roman numeral analysis',
  'K5.4': '12-bar blues',
  'K5.5': 'V–I resolution and ii–V–I',
  'K5.6': 'Relative minor in chord progressions',
  'K6.1': 'The blues scale',
  'K6.2': 'Blue notes',
  'K6.3': 'String bending',
  'K6.4': 'Hammer-ons, pull-offs, slides, vibrato and tapping',
  'K6.5': 'Palm muting',
  'K6.6': 'Double stops, fourth slides and riffs',
  'K6.7': 'Jazz octaves',
  'K7.1': 'Choosing a scale to solo',
  'K7.2': 'Targeting chord tones',
  'K7.3': 'Soloing styles: rock, blues, jazz',
  'K7.4': 'Phrasing: motif and variation',
  'K7.5': 'Ear training',
  'K7.6': 'Improvising by ear: try, listen back, adjust',
} as const;

type Named = keyof typeof en;

const vi: Readonly<Record<Named, string>> = {
  'K0.1': 'Tên và số dây đàn',
  'K0.2': 'Phím đàn và nửa cung',
  'K0.3': 'Đọc tab và sơ đồ hợp âm',
  'K0.4': 'Quy tắc phím 5 và G–B shift',
  'K0.5': 'Tên nốt, thăng giáng và enharmonic',
  'K0.6': 'Shape quãng 8',
  'K0.7': 'Nốt trên dây 6 và dây 5',
  'K0.8': 'Tư thế tay và luyện ngón',
  'K1.1': 'Phách, tempo và bar',
  'K1.2': 'Độ dài nốt và dấu lặng',
  'K1.3': 'Đếm nhịp',
  'K1.4': 'Mẫu quạt dây và alternate picking',
  'K1.5': 'Triplet, swing và shuffle',
  'K2.1': 'Major scale',
  'K2.2': 'Đánh vần scale và key signature',
  'K2.3': 'Quãng: tên và số nửa cung',
  'K2.4': 'Shape quãng trên cần đàn',
  'K2.5': 'Thăng kép, giáng kép và đánh vần nốt',
  'K2.6': 'Quãng ghép: 9, 11, 13',
  'K2.7': 'Natural minor scale',
  'K2.8': 'Relative major và relative minor',
  'K2.9': 'Scale 3 nốt mỗi dây',
  'K3.1': 'Major pentatonic',
  'K3.2': 'Minor pentatonic',
  'K3.3': 'Relative major và minor pentatonic',
  'K3.4': 'Năm box pentatonic',
  'K3.5': 'Nối các box pentatonic và đổi giọng',
  'K3.6': 'Sequence pentatonic',
  'K3.7': 'Chọn major hay minor pentatonic',
  'K4.1': 'Triad (hợp âm ba)',
  'K4.2': 'Power chord',
  'K4.3': 'Hợp âm 7',
  'K4.4': 'Hợp âm mở rộng và hợp âm add',
  'K4.5': 'Open chord (hợp âm dây buông)',
  'K4.6': 'Hợp âm chặn di động',
  'K4.7': 'Inversion và slash chord',
  'K4.8': 'Thay thế và rút gọn hợp âm',
  'K4.9': 'Extension và altered note',
  'K5.1': 'Giọng (key) và tonic',
  'K5.2': 'Hợp âm thuận trong giọng trưởng',
  'K5.3': 'Số La Mã cho hợp âm',
  'K5.4': '12-bar blues',
  'K5.5': 'V–I và ii–V–I',
  'K5.6': 'Relative minor trong vòng hợp âm',
  'K6.1': 'Blues scale',
  'K6.2': 'Blue note',
  'K6.3': 'Bend',
  'K6.4': 'Hammer-on, pull-off, slide, vibrato và tapping',
  'K6.5': 'Palm mute',
  'K6.6': 'Double stop, slide quãng 4 và riff',
  'K6.7': 'Jazz octave',
  'K7.1': 'Chọn scale để solo',
  'K7.2': 'Nốt đích theo hợp âm (chord tone)',
  'K7.3': 'Phong cách solo: rock, blues, jazz',
  'K7.4': 'Xây câu: motif và biến tấu',
  'K7.5': 'Luyện tai',
  'K7.6': 'Ứng tác bằng tai: thử, nghe lại, sửa',
};

export const CONCEPT_NAMES: Readonly<Record<Lang, Readonly<Record<Named, string>>>> = { en, vi };

/** The concept's name in `lang`; an unnamed ID shows as itself. */
export const conceptName = (id: ConceptId, lang: Lang): string =>
  (CONCEPT_NAMES[lang] as Readonly<Record<string, string>>)[id] ?? id;
