import type { PentatonicCopy } from './model';

export const en: PentatonicCopy = {
  title: 'Pentatonic, the Whole Neck',
  summary: 'Five boxes that tile the neck, the joins between them, drills that teach every path, and how to pick the shape for a song.',
  lead:
    'The Pentatonic Map showed you the five boxes. This lesson makes them playable: see how they fit together, cross from one to the next, drill each one on a metronome, and choose the right shape for a song in any key. Five steps, all in A minor until step 4. Click any note to hear it.',
  steps: {
    boxes: {
      title: 'Five boxes tile the neck',
      body: [
        'Each box holds two notes on every string, twelve notes in all, within about four frets. The five boxes sit edge to edge along the neck, and after box 5 the chain starts again 12 frets up.',
        'Every box has the same B-string shift: the pair on the B string sits one fret to the right of where the pattern on the lower strings would put it. That comes from G and B being tuned 4 frets apart instead of 5, not from a new shape to learn.',
      ],
      takeaway: 'Five boxes of two notes per string, edge to edge: one map, not five shapes.',
      tryIt: 'Play box 1 up and down. Then find box 2 by its lowest note on string 6, the second note of box 1 on that string.',
    },
    connect: {
      title: 'Neighbouring boxes share an edge',
      body: [
        'Box 1 and box 2 share six notes, one on each string: the higher note of box 1 on a string is the lower note of box 2 on that string. The same holds for every pair, and box 5 hands over to box 1 an octave up.',
        'So a new box is never learned from zero. Half of it is the edge you already play; you only add the six notes past it.',
      ],
      takeaway: 'On each string, the top note of one box is the bottom note of the next.',
      tryIt: 'Play up box 1, then down box 2 without stopping. Do the same for 2→3 before moving on.',
    },
    sequences: {
      title: 'Sequences teach your hand every path',
      body: [
        'Running a box straight up and down only trains one path. Sequences play the notes in overlapping groups: 1-2-3, 2-3-4, 3-4-5, or skip one: 1-3, 2-4. Your fingers learn every move inside the box, and your ear hears each note against its neighbours.',
        'These are exercises, not licks. Play them in time with the click, slowly enough to make no mistakes, then let the tempo creep up a few BPM each round.',
      ],
      takeaway: 'Groups of 3, groups of 4 and skips, on a click, slow first.',
      tryIt: 'Groups of 3 up box 1 at 60 BPM. Turn on "speed up" and stop at the first tempo where a note smudges.',
    },
    major: {
      title: 'Major key? The same shape, 3 frets lower',
      body: [
        'A major pentatonic uses the same five notes as the minor pentatonic whose root is 3 frets lower, its relative minor. G major pentatonic is E minor pentatonic; C major is A minor.',
        'So for a major key you need no new boxes. Find the major root on string 6, slide down 3 frets, and start box 1 there. Then treat the major root as home: the note you start on, lean on and end on.',
      ],
      takeaway: 'Major key: put box 1 three frets below the major root.',
      tryIt: 'Pick G: box 1 starts at fret 0 (or 12). Play from G to G over the drone and hear it sound major.',
    },
    choose: {
      title: 'Which shape fits this song?',
      body: [
        'Minor song: minor pentatonic on the song\'s root. Major song: the same shape slid 3 frets below its root. Blues over dominant 7th chords: the minor pentatonic on the root still works, and its ♭3 rubbing against the chord\'s 3 is part of the blues sound.',
        'The vamp plays the song\'s I chord. Name its root on string 6, decide minor, major or blues, then click where box 1 starts.',
      ],
      takeaway: 'Minor or blues: start box 1 on the root. Major: start it 3 frets lower.',
      tryIt: 'Get five right in a row, then play the scale over the vamp for each one.',
    },
  },
  scene: {
    boxes: {
      box: 'Box',
      labels: 'Labels',
      degrees: 'Degrees',
      notes: 'Notes',
      play: 'Play the box',
      stop: 'Stop',
      kink: 'Dashed: where the B-string pair would sit if G→B were 5 frets apart like the others',
      caption: 'Box {n}: frets {min}–{max}.',
    },
    connect: {
      pair: 'Boxes',
      pairItem: '{from}→{to}',
      cross: 'Up one, down the next',
      stop: 'Stop',
      caption: 'Boxes {from} and {to} share {count} notes, one on each string.',
      playing: 'Up box {from}, down box {to}.',
    },
    sequences: {
      box: 'Box',
      pattern: 'Pattern',
      patterns: { straight: 'Straight', threes: 'Groups of 3', fours: 'Groups of 4', skip: 'Skip one' },
      direction: 'Direction',
      up: 'Up',
      down: 'Down',
      speedUp: 'Speed up',
      off: 'Off',
      on: '+{n} each round',
      start: 'Start',
      stop: 'Stop',
      tempo: 'Tempo',
      bpm: '{bpm} BPM',
      tab: 'Tab of the drill',
      idle: '{pattern} in box {n}: {count} notes in eighths. Press start.',
      round: 'Round {round} at {bpm} BPM.',
    },
    major: {
      key: 'Major key',
      play: 'Root to root over a drone',
      stop: 'Stop',
      legendMajor: 'Major root',
      legendMinor: 'Where box 1 starts',
      caption: '{key} major: box 1 starts on {minor} at fret {minorFret}, 3 frets below {key} at fret {majorFret}.',
      playing: 'From {key} up to {key} and back, over a low {key}.',
    },
    choose: {
      question: 'The band vamps on {chord}: {kind}. Where does box 1 start on string 6?',
      kinds: { minor: 'a minor song', major: 'a major song', blues: 'a blues' },
      vamp: 'Play the vamp',
      hear: 'Hear the scale over it',
      stop: 'Stop',
      next: 'Next song',
      score: '{right} of {total} · {streak} in a row',
      idle: 'Click a fret on string 6.',
      right: 'Yes: box 1 at fret {fret}, {shape} minor pentatonic.',
      rightMajor: 'Yes: fret {fret}. The {shape} minor shape gives {key} major pentatonic.',
      rightBlues: 'Yes: fret {fret}, {key} minor pentatonic over {chord}. That ♭3 against the chord is the blues.',
      songRoot: 'Fret {fret} is {key}, the root. For a major song, slide the minor shape 3 frets lower.',
      majorTrick: 'Fret {fret} is the trick for {key} major, 3 frets below the root. For this song, start box 1 on {key} itself.',
      other: 'Fret {fret} is {note}. Find {key} on string 6 first.',
    },
  },
  notYetTitle: 'What you do not need yet',
  notYetIntro: 'The five boxes are enough to solo over most rock and blues. These can wait.',
  notYet: [
    { title: 'The blues ♭5, bends and slides', why: 'They decorate these same boxes. They come in the blues lesson.' },
    { title: 'Licks and phrasing', why: 'Sequences train the hand. Shaping phrases comes once you hear chords change under you.' },
    { title: 'Target notes on chord changes', why: 'Landing on the chord\'s own notes needs the chords first.' },
    { title: 'Three notes per string', why: 'Another way to cover the neck, with the full seven-note scale. It comes later.' },
    { title: 'CAGED and other box systems', why: 'Five pentatonic boxes already cover the whole neck; one system at a time.' },
  ],
};
