import type { PentatonicCopy } from './model';

export const vi: PentatonicCopy = {
  title: 'Pentatonic trên toàn cần đàn',
  summary: 'Năm box lát kín cần đàn, chỗ nối giữa chúng, sequence để tay đi được mọi đường, và cách chọn shape cho một bài nhạc.',
  lead:
    'Bản đồ Pentatonic đã cho bạn thấy năm box. Bài này giúp bạn chơi được chúng: xem các box khớp với nhau thế nào, đi từ box này sang box kế, luyện từng box với metronome, và chọn đúng shape cho một bài ở bất kỳ giọng nào. Năm bước, giọng A thứ cho tới bước 4. Bấm vào nốt nào cũng nghe được.',
  steps: {
    boxes: {
      title: 'Năm box lát kín cần đàn',
      body: [
        'Mỗi box có hai nốt trên mỗi dây, tổng cộng mười hai nốt, gọn trong khoảng bốn phím. Năm box nằm sát cạnh nhau dọc cần đàn, và sau box 5 chuỗi box lặp lại ở 12 phím cao hơn.',
        'Box nào cũng có một chỗ lệch nhỏ giống nhau: cặp nốt trên dây B nằm lệch sang phải một phím so với chỗ mà mẫu của các dây dưới lẽ ra đặt nó. Đó là G–B shift, khoảng cách 4 phím giữa dây G và B, không phải một shape mới cần học.',
      ],
      takeaway: 'Năm box, mỗi dây hai nốt, nằm sát cạnh nhau: một tấm bản đồ, không phải năm shape rời.',
      tryIt: 'Chơi box 1 lên rồi xuống. Sau đó tìm box 2 qua nốt thấp nhất của nó trên dây 6, chính là nốt thứ hai của box 1 trên dây đó.',
    },
    connect: {
      title: 'Hai box kề nhau dùng chung một cạnh',
      body: [
        'Box 1 và box 2 dùng chung sáu nốt, mỗi dây một nốt: nốt cao của box 1 trên một dây là nốt thấp của box 2 trên dây đó. Cặp box nào cũng vậy, và box 5 nối sang box 1 ở quãng 8 trên.',
        'Vì thế không bao giờ phải học một box mới từ đầu. Một nửa box là cái cạnh bạn đã chơi rồi; chỉ cần thêm sáu nốt phía sau nó.',
      ],
      takeaway: 'Trên mỗi dây, nốt cao của một box là nốt thấp của box kế tiếp.',
      tryIt: 'Chơi box 1 đi lên, rồi box 2 đi xuống, không dừng. Làm tương tự với 2→3 trước khi đi tiếp.',
    },
    sequences: {
      title: 'Sequence dạy tay mọi đường đi',
      body: [
        'Chạy box thẳng lên thẳng xuống chỉ luyện được một đường. Sequence chơi các nốt theo từng nhóm gối lên nhau: 1-2-3, 2-3-4, 3-4-5, hoặc cách một: 1-3, 2-4. Ngón tay học được mọi bước đi trong box, còn tai nghe được từng nốt bên cạnh các nốt kề nó.',
        'Đây là bài tập, chưa phải lick. Chơi khớp với tiếng click, đủ chậm để không sai nốt nào, rồi để tempo tăng dần vài BPM sau mỗi vòng.',
      ],
      takeaway: 'Bộ 3, bộ 4 và cách một, chơi theo click, chậm trước đã.',
      tryIt: 'Bộ 3 đi lên trong box 1 ở 60 BPM. Bật "tăng tốc" và dừng ở tempo đầu tiên có nốt bị nhòe.',
    },
    major: {
      title: 'Giọng trưởng? Vẫn shape đó, lùi 3 phím',
      body: [
        'Major pentatonic dùng đúng năm nốt của minor pentatonic có root thấp hơn 3 phím, tức relative minor của nó. G major pentatonic chính là E minor pentatonic; C major là A minor.',
        'Vì thế giọng trưởng không cần box mới. Tìm root trưởng trên dây 6, lùi xuống 3 phím và đặt box 1 ở đó. Rồi coi root trưởng là nốt để bắt đầu, nhấn vào và kết thúc.',
      ],
      takeaway: 'Giọng trưởng: đặt box 1 thấp hơn root trưởng 3 phím.',
      tryIt: 'Chọn G: box 1 bắt đầu ở phím 0 (hoặc 12). Chơi từ G tới G trên nền drone và nghe nó vang lên màu trưởng.',
    },
    choose: {
      title: 'Bài này dùng shape nào?',
      body: [
        'Bài giọng thứ: minor pentatonic trên root của bài. Bài giọng trưởng: cũng shape đó, lùi 3 phím dưới root. Blues trên hợp âm dominant 7: minor pentatonic trên root vẫn dùng được, và nốt ♭3 nghe chỏi với nốt 3 của hợp âm chính là một phần của màu blues.',
        'Phần backing chơi hợp âm I của bài. Gọi tên root của nó trên dây 6, xác định là thứ, trưởng hay blues, rồi bấm vào chỗ box 1 bắt đầu.',
      ],
      takeaway: 'Thứ hoặc blues: box 1 bắt đầu trên root. Trưởng: bắt đầu thấp hơn 3 phím.',
      tryIt: 'Trả lời đúng năm câu liên tiếp, rồi với mỗi câu, chơi scale trên phần backing.',
    },
  },
  scene: {
    boxes: {
      box: 'Box',
      labels: 'Nhãn',
      degrees: 'Bậc',
      notes: 'Tên nốt',
      play: 'Phát box',
      stop: 'Dừng',
      kink: 'Nét đứt: chỗ cặp nốt dây B sẽ nằm nếu G→B cũng cách 5 phím như các cặp khác',
      caption: 'Box {n}: phím {min}–{max}.',
    },
    connect: {
      pair: 'Box',
      pairItem: '{from}→{to}',
      cross: 'Lên box này, xuống box kế',
      stop: 'Dừng',
      caption: 'Box {from} và box {to} dùng chung {count} nốt, mỗi dây một nốt.',
      playing: 'Lên box {from}, xuống box {to}.',
    },
    sequences: {
      box: 'Box',
      pattern: 'Mẫu',
      patterns: { straight: 'Thẳng', threes: 'Bộ 3', fours: 'Bộ 4', skip: 'Cách một' },
      direction: 'Chiều',
      up: 'Lên',
      down: 'Xuống',
      speedUp: 'Tăng tốc',
      off: 'Tắt',
      on: '+{n} mỗi vòng',
      start: 'Bắt đầu',
      stop: 'Dừng',
      tempo: 'Tempo',
      bpm: '{bpm} BPM',
      tab: 'Tab của bài luyện',
      idle: '{pattern} trong box {n}: {count} nốt móc đơn. Bấm bắt đầu.',
      round: 'Vòng {round}, {bpm} BPM.',
    },
    major: {
      key: 'Giọng trưởng',
      play: 'Từ root tới root trên drone',
      stop: 'Dừng',
      legendMajor: 'Root trưởng',
      legendMinor: 'Chỗ box 1 bắt đầu',
      caption: '{key} trưởng: box 1 bắt đầu từ {minor} ở phím {minorFret}, thấp hơn {key} ở phím {majorFret} 3 phím.',
      playing: 'Từ {key} lên {key} rồi xuống lại, trên nốt {key} trầm.',
    },
    choose: {
      question: 'Ban nhạc vamp trên hợp âm {chord}: {kind}. Box 1 bắt đầu ở đâu trên dây 6?',
      kinds: { minor: 'một bài giọng thứ', major: 'một bài giọng trưởng', blues: 'một bài blues' },
      vamp: 'Phát vamp',
      hear: 'Nghe scale trên vamp',
      stop: 'Dừng',
      next: 'Bài khác',
      score: 'Đúng {right}/{total} · {streak} câu liên tiếp',
      idle: 'Bấm vào một phím trên dây 6.',
      right: 'Đúng: box 1 ở phím {fret}, {shape} minor pentatonic.',
      rightMajor: 'Đúng: phím {fret}. Shape {shape} minor cho ra {key} major pentatonic.',
      rightBlues: 'Đúng: phím {fret}, {key} minor pentatonic trên {chord}. Nốt ♭3 nghe chỏi với hợp âm chính là màu blues.',
      songRoot: 'Phím {fret} là {key}, root. Với bài giọng trưởng, lùi shape minor xuống 3 phím.',
      majorTrick: 'Phím {fret} là mẹo cho {key} trưởng, thấp hơn root 3 phím. Với bài này, box 1 bắt đầu ngay trên {key}.',
      other: 'Phím {fret} là {note}. Tìm {key} trên dây 6 trước đã.',
    },
  },
  notYetTitle: 'Chưa cần học lúc này',
  notYetIntro: 'Năm box đã đủ để solo trên phần lớn nhạc rock và blues. Những thứ này để sau.',
  notYet: [
    { title: 'Nốt ♭5 của blues, bend và slide', why: 'Chúng trang trí cho chính các box này. Bài blues sẽ dạy.' },
    { title: 'Lick và cách xây câu', why: 'Sequence rèn tay. Xây câu đến khi bạn nghe được hợp âm đổi bên dưới.' },
    { title: 'Nốt đích khi đổi hợp âm', why: 'Muốn đáp vào nốt của hợp âm thì cần học hợp âm trước.' },
    { title: 'Scale 3 nốt mỗi dây', why: 'Một cách khác để phủ cần đàn, với đủ bảy nốt. Học sau.' },
    { title: 'CAGED và các hệ thống box khác', why: 'Năm box pentatonic đã phủ kín cần đàn; mỗi lúc một hệ thống thôi.' },
  ],
};
