import type { PentatonicCopy } from './model';

export const vi: PentatonicCopy = {
  title: 'Pentatonic trên toàn cần đàn',
  summary: 'Năm hộp lát kín cần đàn, chỗ nối giữa chúng, bài luyện để tay đi được mọi đường, và cách chọn hình cho một bài nhạc.',
  lead:
    'Bản đồ Pentatonic đã cho bạn thấy năm hộp. Bài này giúp bạn chơi được chúng: xem các hộp khớp với nhau thế nào, đi từ hộp này sang hộp kế, luyện từng hộp với metronome, và chọn đúng hình cho một bài ở bất kỳ giọng nào. Năm bước, giọng A thứ cho tới bước 4. Bấm vào nốt nào cũng nghe được.',
  steps: {
    boxes: {
      title: 'Năm hộp lát kín cần đàn',
      body: [
        'Mỗi hộp có hai nốt trên mỗi dây, tổng cộng mười hai nốt, gọn trong khoảng bốn phím. Năm hộp nằm sát cạnh nhau dọc cần đàn, và sau hộp 5 chuỗi hộp lặp lại ở 12 phím cao hơn.',
        'Hộp nào cũng có một chỗ lệch nhỏ giống nhau: cặp nốt trên dây B nằm lệch sang phải một phím so với chỗ mà mẫu của các dây dưới lẽ ra đặt nó. Đó là khoảng cách 4 phím giữa dây G và B, không phải một hình mới cần học.',
      ],
      takeaway: 'Năm hộp, mỗi dây hai nốt, nằm sát cạnh nhau: một tấm bản đồ, không phải năm hình rời.',
      tryIt: 'Chơi hộp 1 lên rồi xuống. Sau đó tìm hộp 2 qua nốt thấp nhất của nó trên dây 6, chính là nốt thứ hai của hộp 1 trên dây đó.',
    },
    connect: {
      title: 'Hai hộp kề nhau dùng chung một cạnh',
      body: [
        'Hộp 1 và hộp 2 dùng chung sáu nốt, mỗi dây một nốt: nốt cao của hộp 1 trên một dây là nốt thấp của hộp 2 trên dây đó. Cặp hộp nào cũng vậy, và hộp 5 nối sang hộp 1 ở quãng 8 trên.',
        'Vì thế không bao giờ phải học một hộp mới từ đầu. Một nửa hộp là cái cạnh bạn đã chơi rồi; chỉ cần thêm sáu nốt phía sau nó.',
      ],
      takeaway: 'Trên mỗi dây, nốt cao của hộp k là nốt thấp của hộp k + 1.',
      tryIt: 'Chơi hộp 1 đi lên, rồi hộp 2 đi xuống, không dừng. Làm tương tự với 2→3 trước khi đi tiếp.',
    },
    sequences: {
      title: 'Mẫu luyện ngón dạy tay mọi đường đi',
      body: [
        'Chạy hộp thẳng lên thẳng xuống chỉ luyện được một đường. Mẫu luyện ngón chơi các nốt theo từng nhóm gối lên nhau: 1-2-3, 2-3-4, 3-4-5, hoặc cách một: 1-3, 2-4. Ngón tay học được mọi bước đi trong hộp, còn tai nghe được từng nốt bên cạnh các nốt kề nó.',
        'Đây là bài tập, chưa phải câu solo. Chơi khớp với tiếng click, đủ chậm để không sai nốt nào, rồi để tempo tăng dần vài BPM sau mỗi vòng.',
      ],
      takeaway: 'Bộ 3, bộ 4 và cách một, chơi theo click, chậm trước đã.',
      tryIt: 'Bộ 3 đi lên trong hộp 1 ở 60 BPM. Bật "tăng tốc" và dừng ở tempo đầu tiên có nốt bị nhòe.',
    },
    major: {
      title: 'Giọng trưởng? Vẫn hình đó, lùi 3 phím',
      body: [
        'Pentatonic trưởng dùng đúng năm nốt của pentatonic thứ có nốt nhà thấp hơn 3 phím. G trưởng pentatonic chính là E thứ pentatonic; C trưởng là A thứ.',
        'Vì thế giọng trưởng không cần hộp mới. Tìm nốt nhà trưởng trên dây 6, lùi xuống 3 phím và đặt hộp 1 ở đó. Rồi coi nốt nhà trưởng là nốt để bắt đầu, nhấn vào và kết thúc.',
      ],
      takeaway: 'Giọng trưởng: đặt hộp 1 thấp hơn nốt nhà trưởng 3 phím.',
      tryIt: 'Chọn G: hộp 1 bắt đầu ở phím 0 (hoặc 12). Chơi từ G tới G trên nền nốt ngân và nghe nó vang lên màu trưởng.',
    },
    choose: {
      title: 'Bài này dùng hình nào?',
      body: [
        'Bài giọng thứ: pentatonic thứ trên nốt nhà của bài. Bài giọng trưởng: cũng hình đó, lùi 3 phím dưới nốt nhà. Blues trên hợp âm 7: pentatonic thứ trên nốt nhà vẫn dùng được, và nốt ♭3 cọ vào nốt 3 của hợp âm chính là một phần của màu blues.',
        'Vòng đệm chơi hợp âm chủ của bài. Gọi tên nốt gốc của nó trên dây 6, xác định là thứ, trưởng hay blues, rồi bấm vào chỗ hộp 1 bắt đầu.',
      ],
      takeaway: 'Thứ hoặc blues: hộp 1 bắt đầu trên nốt gốc. Trưởng: bắt đầu thấp hơn 3 phím.',
      tryIt: 'Trả lời đúng năm câu liên tiếp, rồi với mỗi câu, chơi âm giai trên vòng đệm.',
    },
  },
  scene: {
    boxes: {
      box: 'Hộp',
      labels: 'Nhãn',
      degrees: 'Bậc',
      notes: 'Tên nốt',
      play: 'Phát hộp',
      stop: 'Dừng',
      kink: 'Nét đứt: chỗ cặp nốt dây B sẽ nằm nếu G→B cũng cách 5 phím như các cặp khác',
      caption: 'Hộp {n}: phím {min}–{max}.',
    },
    connect: {
      pair: 'Hộp',
      pairItem: '{from}→{to}',
      cross: 'Lên hộp này, xuống hộp kế',
      stop: 'Dừng',
      caption: 'Hộp {from} và hộp {to} dùng chung {count} nốt, mỗi dây một nốt.',
      playing: 'Lên hộp {from}, xuống hộp {to}.',
    },
    sequences: {
      box: 'Hộp',
      pattern: 'Mẫu',
      patterns: { straight: 'Thẳng', threes: 'Bộ 3', fours: 'Bộ 4', skip: 'Cách một' },
      direction: 'Chiều',
      up: 'Lên',
      down: 'Xuống',
      speedUp: 'Tăng tốc',
      off: 'Tắt',
      on: '+{n} mỗi vòng',
      start: 'Bắt đầu',
      stop: 'Dừng',
      tempo: 'Tempo',
      bpm: '{bpm} BPM',
      tab: 'Tab của bài luyện',
      idle: '{pattern} trong hộp {n}: {count} nốt móc đơn. Bấm bắt đầu.',
      round: 'Vòng {round}, {bpm} BPM.',
    },
    major: {
      key: 'Giọng trưởng',
      play: 'Từ nhà tới nhà trên nốt ngân',
      stop: 'Dừng',
      legendMajor: 'Nhà trưởng',
      legendMinor: 'Chỗ hộp 1 bắt đầu',
      caption: '{key} trưởng: hộp 1 bắt đầu từ {minor} ở phím {minorFret}, thấp hơn {key} ở phím {majorFret} 3 phím.',
      playing: 'Từ {key} lên {key} rồi xuống lại, trên nốt {key} trầm.',
    },
    choose: {
      question: 'Ban nhạc đệm hợp âm {chord}: {kind}. Hộp 1 bắt đầu ở đâu trên dây 6?',
      kinds: { minor: 'một bài giọng thứ', major: 'một bài giọng trưởng', blues: 'một bài blues' },
      vamp: 'Phát vòng đệm',
      hear: 'Nghe âm giai trên vòng đệm',
      stop: 'Dừng',
      next: 'Bài khác',
      score: 'Đúng {right}/{total} · {streak} câu liên tiếp',
      idle: 'Bấm vào một phím trên dây 6.',
      right: 'Đúng: hộp 1 ở phím {fret}, {shape} thứ pentatonic.',
      rightMajor: 'Đúng: phím {fret}. Hình {shape} thứ cho ra {key} trưởng pentatonic.',
      rightBlues: 'Đúng: phím {fret}, {key} thứ pentatonic trên {chord}. Nốt ♭3 cọ vào hợp âm chính là màu blues.',
      songRoot: 'Phím {fret} là {key}, nốt gốc. Với bài giọng trưởng, lùi hình thứ xuống 3 phím.',
      majorTrick: 'Phím {fret} là mẹo cho {key} trưởng, thấp hơn nốt gốc 3 phím. Với bài này, hộp 1 bắt đầu ngay trên {key}.',
      other: 'Phím {fret} là {note}. Tìm {key} trên dây 6 trước đã.',
    },
  },
  notYetTitle: 'Những thứ chưa cần lúc này',
  notYetIntro: 'Năm hộp đã đủ để solo trên phần lớn nhạc rock và blues. Những thứ này để sau.',
  notYet: [
    { title: 'Nốt ♭5 của blues, nhéo dây và trượt', why: 'Chúng trang trí cho chính các hộp này. Bài blues sẽ dạy.' },
    { title: 'Câu solo và cách xây câu', why: 'Mẫu luyện ngón rèn tay. Xây câu đến khi bạn nghe được hợp âm đổi bên dưới.' },
    { title: 'Nốt đích khi đổi hợp âm', why: 'Muốn đáp vào nốt của hợp âm thì cần học hợp âm trước.' },
    { title: 'Âm giai 3 nốt mỗi dây', why: 'Một cách khác để phủ cần đàn, với đủ bảy nốt. Học sau.' },
    { title: 'Lưu tempo cao nhất và điểm số', why: 'Tạm thời hãy ghi ra giấy. Chế độ ôn tập chung đến ở cuối lộ trình.' },
    { title: 'CAGED và các hệ thống hộp khác', why: 'Năm hộp pentatonic đã phủ kín cần đàn; mỗi lúc một hệ thống thôi.' },
  ],
};
