import type { BluesCopy } from './model';

export const vi: BluesCopy = {
  title: 'Blues: nốt blue, shuffle và nhéo dây',
  summary: 'Một nốt thêm vào, cảm giác dài–ngắn, mười hai ô nhịp ba hợp âm, và những động tác tay trái làm cây đàn biết hát.',
  lead:
    'Các hộp pentatonic vốn đã nghe hơi blues. Bài này thêm những thứ biến chúng thành blues thật: một nốt đi qua, cảm giác shuffle, khung 12 ô, và nhéo dây, trượt, luyến làm đổi cao độ mà không cần gảy lại. Năm bước, giọng A. Bấm vào nốt nào cũng nghe được.',
  steps: {
    blueNote: {
      title: 'Thêm một nốt: ♭5',
      body: [
        'Thêm một nốt vào pentatonic thứ, nốt ♭5 nằm giữa bậc 4 và bậc 5, là có âm giai blues thứ: 1 ♭3 4 ♭5 5 ♭7. Nốt này nằm trong mọi hộp, cách nốt bên cạnh một phím, nên các hình vẫn giữ nguyên.',
        'Nốt ♭5 là nốt đi qua. Trượt hoặc bước qua nó trên đường từ 4 sang 5; dừng lại và ngân trên nó nghe như chưa xong câu. Blues trưởng cũng làm vậy với nốt ♭3 thêm vào pentatonic trưởng, rồi vuốt lên bậc 3.',
      ],
      takeaway: 'Âm giai blues = pentatonic + một nốt đi qua: ♭5 ở giọng thứ, ♭3 ở giọng trưởng.',
      tryIt: 'Chơi 4 → ♭5 → 5 trong hộp 1 và dừng ở 5. Rồi thử dừng ở ♭5 để nghe vì sao không nên.',
    },
    shuffle: {
      title: 'Shuffle: móc đơn chơi dài–ngắn',
      body: [
        'Chia một phách thành ba phần bằng nhau và đếm "1 trí-ô". Shuffle chơi hai nốt mỗi phách: nốt đầu kéo dài hai trong ba phần, nốt sau chỉ chiếm phần cuối. Dài–ngắn, dài–ngắn.',
        'Móc đơn thẳng thì chia phách làm đôi. Kéo từ thẳng sang shuffle và xem nốt "và" của mỗi phách lùi dần về sau, từ giữa phách tới một phần ba cuối.',
      ],
      takeaway: 'Shuffle = hai phần ba đầu của liên ba, rồi một phần ba cuối.',
      tryIt: 'Đếm "1 trí-ô 2 trí-ô" theo tiếng click, rồi gảy dây A buông chỉ ở "1" và "ô".',
    },
    twelveBar: {
      title: 'Blues 12 ô: ba hợp âm, ba câu',
      body: [
        'Blues 12 ô dùng các hợp âm trên bậc I, IV và V của giọng, tất cả đều là hợp âm 7. Bốn ô I; hai ô IV, hai ô I; rồi V, IV, I, I. Ở giọng A: A7, D7 và E7.',
        'Hai biến thể hay gặp: "đổi sớm" chuyển sang IV ở ô 2 rồi về ngay; "quay vòng" chơi V ở ô 12 để kéo bạn về đầu. Trên toàn bộ tiến trình, A thứ pentatonic đều dùng được: nốt ♭3 và ♭7 của nó cọ vào hợp âm, và sự cọ đó chính là blues.',
      ],
      takeaway: 'I I I I · IV IV I I · V IV I I, toàn hợp âm 7.',
      tryIt: 'Chơi theo và đọc tên hợp âm trước mỗi lần đổi một phách. Rồi bật đổi sớm và quay vòng.',
    },
    bends: {
      title: 'Nhéo tới một nốt thật',
      body: [
        'Nhéo dây là đẩy dây sang ngang để nâng cao độ. Trong pentatonic thứ, các nhéo tự nhiên đi lên một cung tới nốt kế tiếp của âm giai: 4 lên 5, ♭7 lên 1, ♭3 lên 4. Đẩy bằng ngón 3, hai ngón 1 và 2 đỡ phía sau.',
        'Nhéo phải tới nơi. Bấm nốt đích cao hơn hai phím trước, nghe kỹ, rồi nhéo cho tới khi cao độ khớp. Ngoại lệ duy nhất là nhéo nhẹ: ♭3 đẩy lên khoảng một phần tư cung về phía 3, đó là một màu, không phải một đích.',
      ],
      takeaway: 'Nghe nốt đích trước; nhéo thiếu nghe như lạc giọng.',
      tryIt: 'Bấm phím 9 dây G, rồi nhéo phím 7 lên cho tới khi khớp. Sau đó làm bài đố: đủ, thiếu hay thừa?',
    },
    legato: {
      title: 'Luyến lên, luyến xuống, trượt và rung',
      body: [
        'Tay bấm có thể tự đổi cao độ. Luyến lên là đập ngón xuống đủ mạnh để nốt cao hơn kêu; luyến xuống là kéo ngón ra để nốt thấp hơn kêu; trượt là giữ lực ấn và lướt dọc dây. Không động tác nào cần gảy lại.',
        'Rung là lắc đều một nốt ngân quanh cao độ của nó, thường ở nốt cuối câu. Ghép chúng lại, một hộp mười hai nốt bắt đầu biết nói. Tab ghi chúng là h, p, / và ~, còn nhéo là b.',
      ],
      takeaway: 'Gảy một lần, rồi để tay bấm đổi cao độ: đó là giọng của guitar điện.',
      tryIt: 'Chơi chậm câu mẫu trên nền 12 ô. Chỉ gảy các số trơn và nốt nhéo; h, p, r và / thì không gảy.',
    },
  },
  scene: {
    play: 'Phát',
    stop: 'Dừng',
    tempo: 'Tempo',
    bpm: '{bpm} BPM',
    curve: 'Cao độ theo thời gian',
    blueNote: {
      box: 'Hộp',
      scale: 'Âm giai',
      minor: 'A blues thứ',
      major: 'C blues trưởng',
      blue: 'Nốt blue',
      on: 'Bật',
      off: 'Tắt',
      playPhrase: 'Phát câu nhạc',
      legend: 'Nốt blue: {degree}',
      phrase: 'Câu nhạc: {degrees}',
    },
    shuffle: {
      feel: 'Cảm giác',
      straight: 'Thẳng',
      shuffle: 'Shuffle',
      swing: 'Swing',
      trip: 'trí',
      let: 'ô',
      grid: 'Một ô nhịp móc đơn trên lưới liên ba',
      caption: 'Swing {pct}%: móc đơn thứ hai bắt đầu ở {at} của phách.',
    },
    twelveBar: {
      key: 'Giọng',
      quickChange: 'Đổi sớm',
      turnaround: 'Quay vòng',
      on: 'Bật',
      off: 'Tắt',
      form: '12 ô nhịp',
      playing: 'Ô {n}: {chord} ({degree})',
      idle: 'Blues {key}, chơi kiểu shuffle. Bấm phát và đếm ô nhịp.',
    },
    bends: {
      bend: 'Nhéo',
      pair: '{from} → {to}',
      curl: 'nhéo nhẹ ♭3',
      playBend: 'Nốt đích, rồi nhéo',
      caption: '{from} → {to}: nhéo dây {string} ở phím {fret} cho tới khi nghe giống phím {target}.',
      curlCaption: 'Nhéo nhẹ: dây {string}, phím {fret}, đẩy lên khoảng một phần tư cung về phía 3. Không có đích cần tới.',
      quizTitle: 'Kiểm tra tai: nhéo đã tới chưa?',
      listen: 'Phát nốt đích, rồi nhéo',
      outcomes: { flat: 'Thiếu', full: 'Đủ', sharp: 'Thừa' },
      right: 'Đúng: {outcome}.',
      wrong: 'Chưa đúng: đáp án là {outcome}. Phát lại và so sánh.',
      next: 'Câu khác',
      score: 'Đúng {right}/{total}',
    },
    legato: {
      technique: 'Kỹ thuật',
      demos: { hammer: 'Luyến lên', pull: 'Luyến xuống', slide: 'Trượt', vibrato: 'Rung', bendRelease: 'Nhéo và nhả' },
      captions: {
        hammer: 'Gảy nốt thấp, rồi đập ngón xuống nốt cao: bước lên kêu mà không cần gảy lại.',
        pull: 'Gảy nốt cao khi nốt thấp đã bấm sẵn, rồi kéo ngón ra: bước xuống.',
        slide: 'Gảy, rồi giữ lực ấn và lướt lên hai phím: nghe được mọi cao độ ở giữa.',
        vibrato: 'Ngân nốt nhà và lắc đều, cao hơn rồi thấp hơn cao độ của nó một chút.',
        bendRelease: 'Nhéo lên một cung, giữ, rồi nhả dây về chỗ cũ.',
      },
      lick: 'Câu mẫu',
      playLick: 'Câu mẫu trên nền 12 ô',
      tab: 'Tab của câu mẫu',
      marks: 'h luyến lên · p luyến xuống · / trượt · b nhéo · r nhả · ~ rung',
      playing: 'Ô {n}: {chord}',
      lickIdle: 'Câu mẫu vang ở ô 1–2, 5–6 và 9–10, đầu mỗi câu. Những ô còn lại để nghe.',
    },
  },
  notYetTitle: 'Những thứ chưa cần lúc này',
  notYetIntro: 'Blues sâu lắm. Những thứ này để các bài sau.',
  notYet: [
    { title: 'Chặn tiếng, power chord và double stop', why: 'Đó là phần đệm của guitar điện, ở bài sau.' },
    { title: 'Tapping', why: 'Là luyến lên bằng tay phải. Cần luyến sạch trước đã.' },
    { title: 'Đổi nốt theo từng hợp âm', why: 'Nhắm vào nốt của D7 khi đang ở D7 thuộc về bài solo theo hợp âm.' },
    { title: 'Swing ngoài shuffle', why: 'Swing jazz còn lỏng hơn nữa. Shuffle liên ba là chuẩn của blues.' },
    { title: 'Lưu điểm bài kiểm tra tai', why: 'Chế độ ôn tập chung đến ở cuối lộ trình.' },
    { title: 'Tự viết câu solo', why: 'Trước hết hãy nghe và chơi tốt một câu; cách xây câu đến cùng bài solo.' },
  ],
};
