import type { BluesCopy } from './model';

export const en: BluesCopy = {
  title: 'Blues: Blue Notes, Shuffle and Bends',
  summary: 'One extra note, a long–short feel, twelve bars of three chords, and the hand moves that make a guitar sing.',
  lead:
    'The pentatonic boxes already sound bluesy. This lesson adds what turns them into the blues: one passing note, the shuffle feel, the 12-bar form, and bends, slides and hammer-ons that change pitch without picking again. Five steps in A. Click any note to hear it.',
  steps: {
    blueNote: {
      title: 'One extra note: the ♭5',
      body: [
        'Add one note to minor pentatonic, the ♭5 between the 4 and the 5, and you have the minor blues scale: 1 ♭3 4 ♭5 5 ♭7. It sits inside every box, one fret from its neighbours, so the shapes stay the same.',
        'The ♭5 is a passing note. Slide or walk through it on the way between 4 and 5; landing and resting on it sounds unfinished. Major blues does the same with the ♭3 added to major pentatonic, rolled up into the 3.',
      ],
      takeaway: 'Blues scale = pentatonic + one passing note: ♭5 in minor, ♭3 in major.',
      tryIt: 'Play 4 → ♭5 → 5 in box 1 and stop on the 5. Then try stopping on the ♭5 and hear why you should not.',
    },
    shuffle: {
      title: 'Shuffle: eighths played long–short',
      body: [
        'Split a beat into three equal parts and count "1 trip-let". A shuffle plays two notes per beat: the first lasts two of the three parts, the second only the last one. Long–short, long–short.',
        'Straight eighths split the beat in half instead. Drag from straight to shuffle and watch the "and" of each beat move later, from the middle of the beat to the last third.',
      ],
      takeaway: 'Shuffle = the first two thirds of a triplet, then the last third.',
      tryIt: 'Count "1 trip-let 2 trip-let" with the click, then play the open A string on "1" and "let" only.',
    },
    twelveBar: {
      title: 'The 12-bar blues: three chords, three lines',
      body: [
        'The 12-bar blues uses the chords on degrees I, IV and V of the key, all as 7 chords. Four bars of I; two of IV, two of I; then V, IV, I, I. In A: A7, D7 and E7.',
        'Two common changes: the quick change goes to IV in bar 2 and straight back; the turnaround plays V in bar 12 to pull you back to the top. Over all of it, A minor pentatonic works: its ♭3 and ♭7 rub against the chords, and that rub is the blues.',
      ],
      takeaway: 'I I I I · IV IV I I · V IV I I, all 7 chords.',
      tryIt: 'Play along and say the chord name one beat before each change. Then try the quick change and the turnaround.',
    },
    bends: {
      title: 'Bend to a real note',
      body: [
        'A bend pushes the string sideways to raise the pitch. In minor pentatonic the natural bends go up a whole step to the next note of the scale: 4 to 5, ♭7 to 1, ♭3 to 4. Push with your third finger and let the first two help behind it.',
        'A bend has to arrive. Fret the target two frets higher first, listen, then bend until the pitch matches. The one exception is the curl: the ♭3 nudged a quarter tone toward 3, a colour, not a target.',
      ],
      takeaway: 'Hear the target first; a bend that stops short sounds out of tune.',
      tryIt: 'Play fret 9 on the G string, then bend fret 7 up until it matches. Then take the quiz: on pitch, flat or sharp?',
    },
    legato: {
      title: 'Hammer-ons, pull-offs, slides and vibrato',
      body: [
        'Your fretting hand can change the pitch on its own. A hammer-on brings a finger down hard enough to sound a higher note; a pull-off flicks it off to sound a lower one; a slide keeps the pressure on and glides along the string. None of them is picked again.',
        'Vibrato shakes a held note evenly around its pitch, usually on the last note of a phrase. Put them together and a box of twelve notes starts to talk. Tab writes them as h, p, / and ~, and a bend as b.',
      ],
      takeaway: 'Pick once, then let the fretting hand move the pitch: that is the electric guitar voice.',
      tryIt: 'Play the lick slowly over the 12-bar. Pick the plain numbers and the bend; h, p, r and / are not picked.',
    },
  },
  scene: {
    play: 'Play',
    stop: 'Stop',
    tempo: 'Tempo',
    bpm: '{bpm} BPM',
    curve: 'Pitch over time',
    blueNote: {
      box: 'Box',
      scale: 'Scale',
      minor: 'A minor blues',
      major: 'C major blues',
      blue: 'Blue note',
      on: 'On',
      off: 'Off',
      playPhrase: 'Play the phrase',
      legend: 'Blue note: {degree}',
      phrase: 'Phrase: {degrees}',
    },
    shuffle: {
      feel: 'Feel',
      straight: 'Straight',
      shuffle: 'Shuffle',
      swing: 'Swing',
      trip: 'trip',
      let: 'let',
      grid: 'One bar of eighths on a triplet grid',
      caption: 'Swing {pct}%: the second eighth starts {at} of the way through the beat.',
    },
    twelveBar: {
      key: 'Key',
      quickChange: 'Quick change',
      turnaround: 'Turnaround',
      on: 'On',
      off: 'Off',
      form: 'The 12 bars',
      playing: 'Bar {n}: {chord} ({degree})',
      idle: '{key} blues, played as a shuffle. Press play and count the bars.',
    },
    bends: {
      bend: 'Bend',
      pair: '{from} → {to}',
      curl: '♭3 curl',
      playBend: 'Target, then the bend',
      caption: '{from} → {to}: bend string {string} at fret {fret} until it sounds like fret {target}.',
      curlCaption: 'The curl: string {string}, fret {fret}, pushed a quarter tone toward the 3. No target to hit.',
      quizTitle: 'Ear check: did the bend land?',
      listen: 'Play target, then bend',
      outcomes: { flat: 'Flat', full: 'On pitch', sharp: 'Sharp' },
      right: 'Right: {outcome}.',
      wrong: 'Not quite: it was {outcome}. Play it again and compare.',
      next: 'Next bend',
      score: '{right} of {total}',
    },
    legato: {
      technique: 'Technique',
      demos: { hammer: 'Hammer-on', pull: 'Pull-off', slide: 'Slide', vibrato: 'Vibrato', bendRelease: 'Bend and release' },
      captions: {
        hammer: 'Pick the lower note, then hammer the higher one: the step up is heard without a new pick.',
        pull: 'Pick the higher note with the lower one already fretted, then pull off: the step down.',
        slide: 'Pick, then keep pressing and glide two frets up: every pitch in between is heard.',
        vibrato: 'Hold the home note and shake it evenly, a little above and below its pitch.',
        bendRelease: 'Bend up a whole step, hold it, then let the string back down to where it started.',
      },
      lick: 'The lick',
      playLick: 'Lick over the 12-bar',
      tab: 'Tab of the lick',
      marks: 'h hammer-on · p pull-off · / slide · b bend · r release · ~ vibrato',
      playing: 'Bar {n}: {chord}',
      lickIdle: 'The lick plays in bars 1–2, 5–6 and 9–10, the start of each line. Listen in the gaps.',
    },
  },
  notYetTitle: 'What you do not need yet',
  notYetIntro: 'The blues goes deep. These can wait for the next lessons.',
  notYet: [
    { title: 'Palm muting, power chords and double stops', why: 'They are the rhythm side of electric guitar, in the next lesson.' },
    { title: 'Tapping', why: 'A right-hand hammer-on. It needs clean legato first.' },
    { title: 'Changing notes on each chord', why: 'Targeting the notes of D7 over D7 comes with soloing over changes.' },
    { title: 'Swing beyond the shuffle', why: 'Jazz swing loosens the feel further. The triplet shuffle is the blues standard.' },
    { title: 'Saving your ear-check score', why: 'A review mode across lessons comes at the end.' },
    { title: 'Writing your own licks', why: 'First learn to hear and play one well; phrasing comes with soloing.' },
  ],
};
