import type { BluesCopy } from './model';

export const vi: BluesCopy = {
  title: 'Blues: blue note, shuffle và bend',
  summary: 'Một nốt thêm vào, cảm giác dài–ngắn, 12 bar ba hợp âm, và những động tác tay trái làm cây đàn biết hát.',
  lead:
    'Các box pentatonic vốn đã nghe hơi blues. Bài này thêm những thứ biến chúng thành blues thật: một passing note, cảm giác shuffle, khuôn 12-bar, và bend, slide, hammer-on làm đổi cao độ mà không cần gảy lại. Năm bước, giọng A. Bấm vào nốt nào cũng nghe được.',
  steps: {
    blueNote: {
      title: 'Thêm một nốt: ♭5',
      body: [
        'Thêm một nốt vào pentatonic thứ, nốt ♭5 nằm giữa bậc 4 và bậc 5, là có minor blues scale: 1 ♭3 4 ♭5 5 ♭7. Nốt này nằm trong mọi box, cách nốt bên cạnh một phím, nên các shape vẫn giữ nguyên.',
        'Nốt ♭5 là passing note. Slide hoặc bước qua nó trên đường từ 4 sang 5; dừng lại và ngân trên nó nghe như chưa xong câu. Major blues cũng làm vậy với nốt ♭3 thêm vào major pentatonic, rồi slide lên bậc 3.',
      ],
      takeaway: 'Blues scale = pentatonic + một passing note: ♭5 ở giọng thứ, ♭3 ở giọng trưởng.',
      tryIt: 'Chơi 4 → ♭5 → 5 trong box 1 và dừng ở 5. Rồi thử dừng ở ♭5 để nghe vì sao không nên.',
    },
    shuffle: {
      title: 'Shuffle: móc đơn chơi dài–ngắn',
      body: [
        'Chia một phách thành ba phần bằng nhau và đếm "1 trip-let". Shuffle chơi hai nốt mỗi phách: nốt đầu kéo dài hai trong ba phần, nốt sau chỉ chiếm phần cuối. Dài–ngắn, dài–ngắn.',
        'Móc đơn thẳng thì chia phách làm đôi. Kéo từ thẳng sang shuffle và xem nốt "và" của mỗi phách lùi dần về sau, từ giữa phách tới một phần ba cuối.',
      ],
      takeaway: 'Shuffle = hai phần ba đầu của triplet, rồi một phần ba cuối.',
      tryIt: 'Đếm "1 trip-let 2 trip-let" theo tiếng click, rồi gảy dây A buông chỉ ở "1" và "let".',
    },
    twelveBar: {
      title: '12-bar blues: ba hợp âm, ba câu',
      body: [
        '12-bar blues dùng các hợp âm trên bậc I, IV và V của giọng, tất cả đều là hợp âm dominant 7. Bốn bar I; hai bar IV, hai bar I; rồi V, IV, I, I. Ở giọng A: A7, D7 và E7.',
        'Hai biến thể hay gặp: quick change chuyển sang IV ở bar 2 rồi về ngay; turnaround chơi V ở bar 12 để kéo bạn về đầu. Trên toàn bộ vòng hợp âm, A minor pentatonic đều dùng được: nốt ♭3 của nó nghe chỏi với quãng 3 trưởng của các hợp âm, và độ chỏi đó chính là blues.',
      ],
      takeaway: 'I I I I · IV IV I I · V IV I I, toàn hợp âm dominant 7.',
      tryIt: 'Chơi theo và đọc tên hợp âm trước mỗi lần đổi một phách. Rồi bật quick change và turnaround.',
    },
    bends: {
      title: 'Bend tới một nốt thật',
      body: [
        'Bend là đẩy dây sang ngang để nâng cao độ. Trong minor pentatonic, các bend tự nhiên đi lên một cung tới nốt kế tiếp của scale: 4 lên 5, ♭7 lên 1, ♭3 lên 4. Đẩy bằng ngón 3, hai ngón 1 và 2 đỡ phía sau.',
        'Bend phải tới nơi. Bấm nốt đích cao hơn hai phím trước, nghe kỹ, rồi bend cho tới khi cao độ khớp. Ngoại lệ duy nhất là curl: ♭3 đẩy lên khoảng một phần tư cung về phía 3, đó là một màu, không phải một đích.',
      ],
      takeaway: 'Nghe nốt đích trước; bend chưa tới nghe như lạc giọng.',
      tryIt: 'Bấm phím 9 dây G, rồi bend phím 7 lên cho tới khi khớp. Sau đó làm bài đố: đúng, thấp hay cao?',
    },
    legato: {
      title: 'Hammer-on, pull-off, slide và vibrato',
      body: [
        'Tay bấm có thể tự đổi cao độ. Hammer-on là đập ngón xuống đủ mạnh để nốt cao hơn kêu; pull-off là kéo ngón ra để nốt thấp hơn kêu; slide là giữ lực ấn và lướt dọc dây. Không động tác nào cần gảy lại.',
        'Vibrato là lắc đều một nốt đang ngân quanh cao độ của nó, thường ở nốt cuối câu. Ghép chúng lại, một box mười hai nốt bắt đầu biết nói. Tab ghi chúng là h, p, / và ~, còn bend là b.',
      ],
      takeaway: 'Gảy một lần, rồi để tay bấm đổi cao độ: đó là giọng của guitar điện.',
      tryIt: 'Chơi chậm lick trên nền 12-bar. Chỉ gảy các số trơn và nốt bend; h, p, r và / thì không gảy. Rồi bấm Lick mới, hoặc đổi giọng hay box, và đọc tab mới.',
    },
  },
  scene: {
    play: 'Phát',
    stop: 'Dừng',
    tempo: 'Tempo',
    bpm: '{bpm} BPM',
    curve: 'Cao độ theo thời gian',
    blueNote: {
      box: 'Box',
      scale: 'Scale',
      minor: 'A minor blues',
      major: 'C major blues',
      blue: 'Blue note',
      on: 'Bật',
      off: 'Tắt',
      playPhrase: 'Phát câu nhạc',
      legend: 'Blue note: {degree}',
      phrase: 'Câu nhạc: {degrees}',
    },
    shuffle: {
      feel: 'Cảm giác',
      straight: 'Thẳng',
      shuffle: 'Shuffle',
      swing: 'Swing',
      trip: 'trip',
      let: 'let',
      grid: 'Một bar móc đơn trên lưới triplet',
      caption: 'Swing {pct}%: móc đơn thứ hai bắt đầu ở {at} của phách.',
    },
    twelveBar: {
      key: 'Giọng',
      quickChange: 'Quick change',
      turnaround: 'Turnaround',
      on: 'Bật',
      off: 'Tắt',
      form: '12 bar',
      playing: 'Bar {n}: {chord} ({degree})',
      idle: 'Blues {key}, chơi kiểu shuffle. Bấm phát và đếm bar.',
    },
    bends: {
      bend: 'Bend',
      pair: '{from} → {to}',
      curl: 'curl ♭3',
      playBend: 'Nốt đích, rồi bend',
      caption: '{from} → {to}: bend dây {string} ở phím {fret} cho tới khi nghe giống phím {target}.',
      curlCaption: 'Curl: dây {string}, phím {fret}, đẩy lên khoảng một phần tư cung về phía 3. Không có đích cần tới.',
      quizTitle: 'Kiểm tra tai: bend đã tới chưa?',
      listen: 'Phát nốt đích, rồi bend',
      outcomes: { flat: 'Thấp', full: 'Đúng', sharp: 'Cao' },
      right: 'Đúng: {outcome}.',
      wrong: 'Chưa đúng: đáp án là {outcome}. Phát lại và so sánh.',
      next: 'Câu khác',
      score: 'Đúng {right}/{total}',
    },
    legato: {
      technique: 'Kỹ thuật',
      demos: { hammer: 'Hammer-on', pull: 'Pull-off', slide: 'Slide', vibrato: 'Vibrato', bendRelease: 'Bend & release' },
      captions: {
        hammer: 'Gảy nốt thấp, rồi đập ngón xuống nốt cao: bước lên kêu mà không cần gảy lại.',
        pull: 'Gảy nốt cao khi nốt thấp đã bấm sẵn, rồi kéo ngón ra: bước xuống.',
        slide: 'Gảy, rồi giữ lực ấn và lướt lên hai phím: nghe được mọi cao độ ở giữa.',
        vibrato: 'Ngân root và lắc đều, cao hơn rồi thấp hơn cao độ của nó một chút.',
        bendRelease: 'Bend lên một cung, giữ, rồi release, nhả dây về chỗ cũ.',
      },
      lick: 'Lick',
      key: 'Giọng',
      box: 'Box',
      newLick: 'Lick mới',
      playLick: 'Lick trên nền 12-bar',
      tab: 'Tab của lick',
      marks: 'h hammer-on · p pull-off · / slide · b bend · r release · ~ vibrato',
      playing: 'Bar {n}: {chord}',
      lickIdle: 'Lick vang ở bar 1–2, 5–6 và 9–10, đầu mỗi câu. Những bar còn lại để nghe.',
    },
  },
  notYetTitle: 'Chưa cần học lúc này',
  notYetIntro: 'Blues sâu lắm. Những thứ này để các bài sau.',
  notYet: [
    { title: 'Palm mute, power chord và double stop', why: 'Đó là phần đệm của guitar điện, ở bài sau.' },
    { title: 'Tapping', why: 'Là hammer-on bằng tay phải. Cần hammer-on và pull-off sạch trước đã.' },
    { title: 'Đổi nốt theo từng hợp âm', why: 'Nhắm vào nốt của D7 khi đang ở D7 thuộc về bài solo theo hợp âm.' },
    { title: 'Swing ngoài shuffle', why: 'Swing trong jazz đổi tỉ lệ dài–ngắn theo tempo và phong cách. Shuffle theo triplet là chuẩn của blues.' },
    { title: 'Lưu điểm bài kiểm tra tai', why: 'Chế độ ôn tập chung đến ở cuối lộ trình.' },
    { title: 'Tự viết lick', why: 'Trước hết hãy nghe và chơi tốt một câu; cách xây câu đến cùng bài solo.' },
  ],
};
